/* APÉRO Tijdreis — data per wereld.
   Gegenereerd uit ~/apero-identity/onderzoek/*.md (## Tijdlijn + ## Leuke feitjes). */
const TIJDREIS = {
  spanje: {
    naam: 'Spanje', sub: 'De revival', romein: 'III',
    foto: 'assets/landen/spanje.jpg', kleur: 'terracotta',
    intro: 'De drank van opa werd de hipste van Spanje.',
    weetjes: [
      'De gilda heet naar Rita Hayworths filmrol uit 1946: net als zij is het hapje zout, pittig en een tikje groen.',
      'Antoni Gaudí ontwierp de intieme salon van Café Torino (1902), een Barcelonese bar die volledig aan vermout was gewijd.',
      "Een caña is bewust klein, zo'n 18 tot 20 centiliter: het bier moet op zijn voordat het lauw wordt.",
      'Txotx, de kreet waarmee in Baskische ciderhuizen een nieuw vat wordt aangeslagen, betekent letterlijk tandenstoker.',
      'Spanje telt grofweg één bar per 175 tot 210 inwoners, meer dan enig ander EU-land; Calvià op Mallorca heeft er zelfs één per 64 inwoners.',
      'Het woord tapa komt van tapar, bedekken: het hapje lag als dekseltje op het glas, tegen stof en fruitvliegjes boven de sherry.',
      'In Granada en León krijg je bij elke caña nog altijd een gratis tapa; bestel je drie rondes, dan heb je feitelijk gegeten.'
    ],
    tijdlijn: [
      { jaar: '13e eeuw', tekst: 'Onder de Moren heet Jerez "Sherish", de naam waaruit het woord sherry ontstaat; de regio exporteert al wijn.' },
      { jaar: '1221-1284', tekst: 'Volgens de legende verplicht koning Alfonso X taveernes wijn alleen met een klein hapje te serveren: de geboortemythe van de tapa.' },
      { jaar: 'Middeleeuwen', tekst: "In Asturias en Baskenland wordt al zo'n duizend jaar cider gemaakt; sagardotegi en chigre worden vaste ontmoetingsplekken." },
      { jaar: '1786', tekst: 'Antonio Benedetto Carpano introduceert in Turijn de eerste moderne zoete vermout, die snel populair wordt aan het hof.' },
      { jaar: '1884', tekst: 'Yzaguirre wordt opgericht in Reus, dat met tientallen producenten uitgroeit tot de vermouthoofdstad van Spanje.' },
      { jaar: 'eind 19e eeuw', tekst: 'Italiaanse immigranten maken vermout populair in Barcelona; het wordt de zondagsdrank van Catalaanse families na de mis.' },
      { jaar: '1902', tekst: 'Café Torino opent in Barcelona, een art-nouveautempel voor vermout waaraan Gaudí en Puig i Cadafalch meewerkten; in 1911 sluit de zaak alweer.' },
      { jaar: '1914', tekst: 'Vermouth Miró wordt opgericht in Reus en groeit uit tot een van de landelijke referentiemerken.' },
      { jaar: 'jaren 40', tekst: 'In Bar Casa Vallés in San Sebastián ontstaat volgens de overlevering de gilda, genoemd naar Rita Hayworths filmrol uit 1946.' },
      { jaar: 'jaren 60-70', tekst: 'Massatoerisme en welvaart maken bier de volksdrank; de caña met tapa wordt het standaardritueel van de Spaanse bar.' },
      { jaar: '1979', tekst: 'Sherry-export piekt op bijna 180 miljoen liter, het historische hoogtepunt van de categorie.' },
      { jaar: '1986', tekst: 'Spanje treedt toe tot de EEG, exportsubsidies voor sherry verdwijnen en de krimp van de categorie versnelt.' },
      { jaar: 'jaren 90', tekst: 'De rebujito (manzanilla met citroenlimonade) verovert de Feria de Abril en verdringt het pure glas fino.' },
      { jaar: 'rond 2013', tekst: 'Jonge Barcelonezen ontketenen de vermut-renaissance; Morro Fi en Casa Mariol maken de hora del vermut weer hip en Catalaans.' },
      { jaar: 'jaren 2010', tekst: 'Vanuit Alicante verspreidt tardeo (uitgaan in de middag) zich over Spanje; na corona groeit de trend verder door.' },
      { jaar: '2021', tekst: 'De Real Academia Española neemt het woord "rebujito" officieel op in het woordenboek.' },
      { jaar: '2024', tekst: 'UNESCO erkent de Asturische cidercultuur, inclusief het escanciar, als immaterieel cultureel erfgoed.' },
      { jaar: '2026', tekst: 'Regelmatig alcoholgebruik onder Spaanse 15- tot 24-jarigen is gedaald tot 17,9 procent; alcoholvrij en laag-alcoholisch groeien door.' }
    ]
  },
  italie: {
    naam: 'Italië', sub: 'Het podium', romein: 'I',
    foto: 'assets/landen/italie.jpg', kleur: 'burro',
    intro: 'Het aperitivo is geen pauze van het leven, het is het optreden.',
    weetjes: [
      'De eerste vermout dateert uit 1786: Carpano opende zijn zaak tegenover het paleis van Turijn en stuurde een kist naar de koning.',
      'De receptuur van Campari is nog altijd geheim en bevat meer dan 60 natuurlijke ingrediënten, van kruiden tot vruchtenschillen.',
      'Een klein glas wijn heet in Venetië een ombra: wijnverkopers schoven hun kraam mee met de schaduw van de campanile, zo bleef de wijn koel.',
      'Sbagliato betekent verkeerd: de beroemdste vergissing uit de cocktailgeschiedenis ontstond in 1972 in Bar Basso, waar de spumante naast de gin stond.',
      'Barman Fosco Scarselli gaf de eerste Negroni in 1919 een sinaasappelschil in plaats van citroen: zo zag je dat dit geen Americano was.',
      'Het kegelvormige flesje Campari Soda uit 1932 is ontworpen door futurist Fortunato Depero en is nooit wezenlijk veranderd.',
      'Aperol bevat maar 11 procent alcohol; in Duitsland werd het tot 2021 op 15 procent gebotteld om de statiegeldwet te omzeilen.'
    ],
    tijdlijn: [
      { jaar: '1e eeuw', tekst: 'Romeinse banketten beginnen met de gustatio, lichte hapjes bij mulsum, met honing gezoete wijn.' },
      { jaar: '5e eeuw', tekst: 'Vroegste gedocumenteerde vermeldingen van aperitieve dranken, onder meer in de Philokalia.' },
      { jaar: '1786', tekst: 'Antonio Benedetto Carpano introduceert in Turijn de eerste moderne zoete vermout, die snel populair wordt aan het koninklijk hof.' },
      { jaar: 'eind 18e eeuw', tekst: 'Vermout verschuift in Italië van medicijn naar aperitief en modieuze Turijnse cafés schenken het de klok rond.' },
      { jaar: '1815-1866', tekst: 'Onder Habsburgs bestuur in Veneto vragen Oostenrijkse soldaten om een scheut water (spritzen) in de lokale wijn: de oer-spritz.' },
      { jaar: '1860', tekst: 'Gaspare Campari ontwikkelt zijn rode bitter met een geheime receptuur van kruiden, schillen en specerijen.' },
      { jaar: '1862', tekst: 'Campari vestigt zich in Milaan en runt een café tegenover de Duomo; Milaan wordt de tweede hoofdstad van de aperitivo.' },
      { jaar: '1870', tekst: 'In de winkel van Carpano ontstaat Punt e Mes: vermout met een half deel kinabitter, volgens de merkoverlevering genoemd naar beursjargon.' },
      { jaar: '1915', tekst: 'Davide Campari opent Camparino in de Galleria Vittorio Emanuele II, tot vandaag hét aperitivo-instituut van Milaan.' },
      { jaar: '1919', tekst: 'In Caffè Casoni in Florence vraagt Camillo Negroni om gin in plaats van soda in zijn Americano: de eerste Negroni.' },
      { jaar: '1919', tekst: 'De gebroeders Luigi en Silvio Barbieri lanceren Aperol in Padua.' },
      { jaar: '1920', tekst: 'De gebroeders Mario en Vittorio Pilla lanceren in Venetië de bitter Select, die uitgroeit tot de basis van de spritz veneziano.' },
      { jaar: '1932', tekst: 'Campari brengt de Campari Soda uit in het kegelvormige flesje van futurist Fortunato Depero, het eerste voorgemixte aperitief.' },
      { jaar: 'jaren 1950', tekst: 'De spritz met prosecco en soda wordt de standaard in Veneto.' },
      { jaar: '1961-1965', tekst: 'Italië krijgt zijn alcoholvrije aperitieven: Bitter Sanpellegrino, het latere Sanbittèr (1961), en Crodino (bedacht 1964, geproduceerd vanaf 1965).' },
      { jaar: '1972', tekst: 'Mirko Stocchetto van Bar Basso in Milaan pakt per ongeluk mousserende wijn in plaats van gin: de Negroni Sbagliato is geboren.' },
      { jaar: '1985', tekst: 'De reclameslogan "Milano da bere" van Amaro Ramazzotti maakt de aperitivo tot symbool van het jachtige, welvarende Milaan.' },
      { jaar: '1995', tekst: 'De happy hour waait over uit de VS en het VK; ondernemer Vinicio Valdo bouwt hem in Milaan om tot apericena met gratis buffet.' },
      { jaar: '2003', tekst: 'Campari neemt Barbero 1891 over, eigenaar van Aperol, en maakt van de Aperol Spritz een wereldwijd exportproduct.' },
      { jaar: '2026', tekst: 'De Aperol Spritz Index legt de prijskloof bloot: 2 euro in Napels tegenover 16,66 euro bij de topbars van Milaan.' }
    ]
  },
  frankrijk: {
    naam: 'Frankrijk', sub: 'De pauze', romein: 'II',
    foto: 'assets/landen/frankrijk.jpg', kleur: 'salvia',
    intro: 'In Frankrijk staat het aperitief gewoon op de klok.',
    weetjes: [
      'Fransen drinken vrijwel alle pastis zelf op: van 90 miljoen liter wereldwijd in 2017 ging 83 miljoen liter door Franse kelen, 92 procent.',
      'Pastis drink je met circa vijf delen koud water op één deel drank; door de anijsolie kleurt het glas direct melkachtig troebel.',
      'Fransen eten circa 70.000 ton saucisson per jaar, omgerekend 2,2 kilo per seconde, en zijn daarmee de grootste saucissoneters ter wereld.',
      "Kanunnik Félix Kir was priester, verzetsman én burgemeester van Dijon; klanten bestelden eerst een glas 'zoals bij kanunnik Kir'.",
      'Dubonnet werd in 1846 niet als borrel bedacht maar als truc om Franse soldaten hun bittere kinine tegen malaria te laten innemen.',
      'Chips zijn apéro-hapje nummer één: 75 procent van de Fransen eet ze vaak of altijd bij de borrel, 41 procent noemt ze onmisbaar.',
      'De grootste apéro géant trok in mei 2010 ruim 10.000 deelnemers naar Nantes, opgetrommeld via één Facebook-evenement zonder organisator.'
    ],
    tijdlijn: [
      { jaar: '5e eeuw', tekst: 'De vroegste gedocumenteerde aperitiefpraktijk duikt op in de Philokalia; het woord apéritif komt van het Latijnse aperire, openen.' },
      { jaar: '1786', tekst: 'Antonio Benedetto Carpano introduceert in Turijn de eerste moderne zoete vermout, de voorloper van alle aperitiefwijnen.' },
      { jaar: '1846', tekst: 'De Parijse chemicus Joseph Dubonnet lanceert zijn kina-aperitief Dubonnet, bedoeld om malariabestrijder kinine drinkbaar te maken.' },
      { jaar: '1872', tekst: 'De broers Paul en Raymond Lillet stichten Maison Lillet in Podensac bij Bordeaux: wijn geïnfuseerd met sinaasappelschillen en kina.' },
      { jaar: '1873', tekst: 'De familie Violet creëert Byrrh in de Roussillon: versterkte rode wijn met kina, cacao, koffie en bittersinaasappel.' },
      { jaar: '1889', tekst: 'Fernand Moureaux creëert Suze, de gele gentiaanbitter met wortels van de hoogvlaktes van de Auvergne.' },
      { jaar: '1904', tekst: 'In Café Montchapet in Dijon ontstaat naar verluidt de blanc-cassis, de latere kir, per ongeluk geschonken aan burgemeester Barabant.' },
      { jaar: '1915', tekst: 'Frankrijk verbiedt absint en alle dranken boven 16 procent alcohol; Marseillanen gaan zelf anijsdrank mixen.' },
      { jaar: '1932', tekst: 'Paul Ricard commercialiseert pastis onder eigen naam als de echte pastis uit Marseille.' },
      { jaar: '1940', tekst: 'Het Vichy-regime verbiedt per decreet van 23 augustus de verkoop van pastis opnieuw; de productie ligt jarenlang stil.' },
      { jaar: '1945', tekst: 'Kanunnik Félix Kir wordt burgemeester van Dijon en maakt blanc-cassis de officiële welkomstdrank van het stadhuis.' },
      { jaar: '1951', tekst: 'Pastis mag weer volwaardig verkocht worden; Ricard draait weer op volle kracht en Pernod lanceert Pernod 51, vanaf 1954 Pastis 51.' },
      { jaar: '1951', tekst: 'Cassisproducent Lejay-Lagoute krijgt schriftelijk exclusief recht om de naam van kanunnik Kir commercieel te gebruiken.' },
      { jaar: '1975', tekst: 'Aartsrivalen Pernod en Ricard fuseren tot Pernod Ricard, tot vandaag een van de grootste drankconcerns ter wereld.' },
      { jaar: '1976', tekst: 'Het woord kir wordt officieel opgenomen in het Franse woordenboek.' },
      { jaar: '1984', tekst: 'Ricard verkoopt zijn miljardste fles pastis.' },
      { jaar: 'jaren 2000', tekst: 'De apéritif dînatoire breekt door: de borrel met uitgebreide hapjes vervangt steeds vaker het diner.' },
      { jaar: '2009', tekst: 'In Nantes ontstaat de apéro géant: via Facebook bijeengeroepen massa-aperitieven op stadspleinen, tot tienduizend deelnemers.' },
      { jaar: 'mei 2010', tekst: 'Na een dodelijk slachtoffer bij een apéro géant in Nantes grijpen de Franse autoriteiten in tegen het fenomeen.' },
      { jaar: '2020', tekst: 'Tijdens de lockdown ontstaat de apéro-visio: 30 procent van de Fransen borrelt via video, onder 35 jaar zelfs 45 procent.' }
    ]
  },
  anijsgordel: {
    naam: 'De anijsgordel', sub: 'Griekenland, Turkije & Libanon', romein: 'IV',
    foto: 'assets/landen/anijsgordel.jpg', kleur: 'panna2',
    intro: 'Ouzo, rakı en arak: de drank wordt zwakker gemaakt, en juist dat is het ritueel.',
    weetjes: [
      'Rakı heet in Turkije aslan sütü, leeuwenmelk: melkwit door het water, en met de kracht van een leeuw.',
      'Het melkwit worden heeft een officiële natuurkundige naam: het ouzo-effect. Anethol lost op in alcohol maar niet in water.',
      'Aan de rakı sofrası proost je met de onderkant van je glas tegen dat van de ander: teken dat iedereen aan tafel gelijk is.',
      'De vaste openingscombinatie bij rakı is witte kaas met meloen: zout plus zoet vangt de anijs perfect op.',
      'Tot 1988 mocht tsipouro niet in flessen verkocht worden: alleen wijnboeren mochten twee dagen per jaar stoken, de tweedaagse stokers.',
      'Op Kreta schenkt bijna elke taverne na het eten een gratis karafje tsikoudia, als teken van vriendschap en respect.',
      "Duitsers zijn de grootste ouzo-drinkers buiten Griekenland: Duitsland importeert jaarlijks zo'n 1,3 miljoen dozen ouzo."
    ],
    tijdlijn: [
      { jaar: '14e eeuw', tekst: 'Volgens de overlevering distilleren monniken op de berg Athos de eerste tsipouro uit druivendraf, aanvankelijk als medicijn.' },
      { jaar: '15e eeuw', tekst: 'Tsipouro verspreidt zich vanuit Athos naar Macedonië, Epirus, Thessalië, Thracië en Kreta.' },
      { jaar: '1510-1514', tekst: 'Het woord rakı duikt op in het Ottomaanse gedicht Beng ü Bâde van Fuzuli.' },
      { jaar: 'rond 1555', tekst: 'In Constantinopel opent het eerste gedocumenteerde koffiehuis van de regio, de oervorm van het kafeneio.' },
      { jaar: '1630', tekst: 'Reiziger Evliya Çelebi beschrijft rakı en de drinkcultuur eromheen in het Ottomaanse Rijk.' },
      { jaar: '17e eeuw', tekst: 'Alleen al Thessaloniki telt meer dan 300 koffiehuizen; het kafeneio wordt een Griekse instelling.' },
      { jaar: 'begin 19e eeuw', tekst: 'Families in Plomari op Lesbos beginnen ouzo te stoken op de manier die er nu nog wordt gebruikt.' },
      { jaar: '1856', tekst: 'Nikolaos Katsaros sticht in Tyrnavos de eerste ouzo-distilleerderij van Griekenland.' },
      { jaar: '1915', tekst: 'Frankrijk verbiedt absint; ouzo profileert zich als absintvervanger zonder alsem en pastis ontstaat later in hetzelfde gat.' },
      { jaar: '1932', tekst: 'Paul Ricard lanceert zijn pastis in Marseille; in Griekenland wordt distillatie in koperen ketels de standaard voor ouzo.' },
      { jaar: '1944', tekst: 'Fabrieksmatige rakı-productie start in İzmir; rakı wordt definitief massaproduct in Turkije.' },
      { jaar: '1988', tekst: 'Griekenland legaliseert het bottelen en landelijk verkopen van tsipouro; het tsipouradiko groeit uit tot stadsfenomeen.' },
      { jaar: '2004', tekst: 'Turkije privatiseert de drankendivisie van Tekel; Yeni Rakı gaat voor 292 miljoen dollar naar Mey İçki, sinds 2011 onderdeel van Diageo.' },
      { jaar: '2006', tekst: 'Ouzo krijgt op 25 oktober EU-bescherming: alleen Griekenland en Cyprus mogen de naam gebruiken.' },
      { jaar: '2010-2017', tekst: 'Griekse crisis en accijnsverhogingen duwen jonge Grieken van ouzo naar goedkoper tsipouro.' },
      { jaar: 'jaren 2010-2020', tekst: "Premiumgolf: kleinschalige ouzo's, gerijpte tsipouro's en craft-arak uit de Bekaa-vallei veroveren cocktailbars." }
    ]
  },
  portugal: {
    naam: 'Portugal', sub: 'De verrassing', romein: 'V',
    foto: 'assets/landen/portugal.jpg', kleur: 'mattone',
    intro: 'Portugal exporteerde zijn beste verhaal en hield zijn beste geheim.',
    weetjes: [
      'Tremoços eet je met techniek: je bijt een spleetje in het taaie velletje en knijpt de boon zo je mond in.',
      'Peixinhos da horta, gefrituurde sperziebonen, reisden in de 16e eeuw met missionarissen mee naar Japan en gelden als voorloper van tempura.',
      "Taylor's Chip Dry uit 1934 was de eerste droge witte port ooit, nu dé basis voor de porto tónico met ijs, citroen en munt.",
      'Bier bestel je niet per merk maar per maat: een imperial in Lissabon heet in Porto een fino, een mini is een flesje van 20 centiliter.',
      "A Ginjinha aan het Rossio schenkt sinds 1840 hetzelfde familierecept; de vraag 'com ou sem elas?' betekent: met of zonder kersen in je glas.",
      'Ramirez, opgericht in 1853, is de oudste nog draaiende visconservenfabriek van Europa en begon met sardines in olijfolie.',
      'Chouriço assado komt op een aardewerken schaaltje met brandende aguardente naar je tafel: je flambeert je borrelworst zelf.'
    ],
    tijdlijn: [
      { jaar: 'ca. 100 v.Chr.', tekst: 'Romeinen planten wijngaarden in het noordwesten van het huidige Portugal; de Minho geldt als een van de oudste wijnstreken ter wereld.' },
      { jaar: '1143', tekst: 'Portugal wordt een onafhankelijk koninkrijk en wijn is vanaf het begin een economische pijler.' },
      { jaar: '1703', tekst: 'Het Methuen-verdrag met Engeland geeft Portugese wijn lage invoerrechten en jaagt de porthandel aan.' },
      { jaar: '1756', tekst: 'De markies van Pombal bakent de Douro-vallei af als een van de eerste beschermde wijnregio\'s ter wereld.' },
      { jaar: '1840', tekst: 'De Galicische monnik Francisco Espinheira begint in Lissabon ginjinha te schenken; A Ginjinha aan het Rossio bestaat nog steeds.' },
      { jaar: '1853', tekst: 'Ramirez opent de eerste visconservenfabriek van Portugal, nu de oudste nog producerende van Europa.' },
      { jaar: 'jaren 1870', tekst: 'Phylloxera verwoest de wijngaarden van de Minho en de Douro; herstel volgt met Amerikaanse onderstokken.' },
      { jaar: 'begin 1900', tekst: 'Galicische immigranten runnen in Lissabon tascas die half kruidenier, half taveerne zijn; de petisco-cultuur krijgt er vorm.' },
      { jaar: '1908', tekst: 'De Vinho Verde-regio wordt bij wet van 18 september afgebakend.' },
      { jaar: '1927', tekst: 'Het merk Super Bock wordt geregistreerd en gelanceerd door de Companhia União Fabril Portuense in Porto.' },
      { jaar: '1934', tekst: "Taylor's blendt Chip Dry, de eerste droge witte aperitiefport, de basis voor de latere porto tónico." },
      { jaar: '1914-1945', tekst: 'De conservenindustrie bloeit door beide wereldoorlogen als leverancier van soldatenrantsoenen; rond 1938 zijn er zo\'n 150 fabrieken.' },
      { jaar: '1940', tekst: 'Sagres wordt gelanceerd voor de Portugese Wereldtentoonstelling; onder de dictatuur groeit het bierduopolie Super Bock-Sagres.' },
      { jaar: 'jaren 1980-1990', tekst: 'Dieptepunt van de conservencrisis: van de circa 150 fabrieken uit de hoogtijdagen blijven er ongeveer 20 over.' },
      { jaar: '2010', tekst: 'Henrique Vaz Pato opent Sol e Pesca in Cais do Sodré, een voormalige hengelsportwinkel die boegbeeld wordt van het tinned-fish-revival.' },
      { jaar: '2014', tekst: 'De Time Out Market opent in de Mercado da Ribeira in Lissabon; petiscos worden een toeristisch product.' },
      { jaar: 'jaren 2010', tekst: 'Porthuizen zetten campagnematig in op de porto tónico als Portugees antwoord op de gin-tonic.' },
      { jaar: '2020', tekst: "Taylor's lanceert een digitale campagne rond Chip Dry & Tonic en later de eerste witte port-tonic in blik." },
      { jaar: 'jaren 2020', tekst: 'Nieuwe generatie koks opent moderne tascas als Taberna Sal Grosso terwijl klassieke tascas sluiten door huurstijgingen.' }
    ]
  },
  marokko: {
    naam: 'Marokko', sub: 'De schenkende hand', romein: 'VI',
    foto: 'assets/landen/marokko.jpg', kleur: 'espresso',
    intro: 'Het aperitief is geen drank, het is de schenkende hand.',
    weetjes: [
      'Atay dankt zijn doorbraak aan een oorlog: toen de Krimoorlog in 1854 de Baltische havens sloot, leidden de Britten hun gunpowder-thee om naar Marokko.',
      'Het hoog inschenken is geen show: de val jaagt de blaadjes naar de bodem en belucht de thee, en de schuimkraag bewijst een goed gezette pot.',
      'De drieglazenregel: het eerste glas bitter als het leven, het tweede sterk als de liefde, het derde zacht als de dood. Alle drie afslaan is onbeleefd.',
      'Anders dan bij vrijwel elk drankritueel ter wereld schenkt in Marokko traditioneel het mannelijke gezinshoofd de thee, niet de vrouw des huizes.',
      'Mahia betekent letterlijk levenswater, precies dezelfde betekenis als eau-de-vie, whisky (uisge beatha) en aquavit.',
      'In Volubilis vonden archeologen Romeinse druivenpersen van tweeduizend jaar oud: Marokko maakte wijn vóór de islam er was.',
      'Café Hafa in Tanger (1921) schenkt al ruim een eeuw vrijwel alleen muntthee; Paul Bowles, de Beatles en de Rolling Stones dronken er.'
    ],
    tijdlijn: [
      { jaar: 'ca. 25 v.Chr.', tekst: 'Romeinen vestigen zich in Volubilis bij het huidige Meknès en bouwen het uit tot wijnproductiecentrum met export over de Middellandse Zee.' },
      { jaar: '7e-8e eeuw', tekst: 'De islam bereikt Marokko en het alcoholverbod wordt de religieuze norm, al verdwijnt drank nooit helemaal uit het land.' },
      { jaar: '18e eeuw', tekst: 'Britse handelaren introduceren gunpowder groene thee in Marokko via de havensteden.' },
      { jaar: 'jaren 1840', tekst: 'De Britse reiziger James Richardson beschrijft als een van de eersten een Marokkaanse theeceremonie.' },
      { jaar: '1854', tekst: 'De Krimoorlog sluit de Baltische havens; de Britse East India Company leidt gunpowder-thee om naar Marokko, een enorme impuls voor atay.' },
      { jaar: '1856', tekst: 'Het Brits-Marokkaanse handelsverdrag opent de markt verder; in de twintig jaar erna verviervoudigt de thee-import.' },
      { jaar: '19e eeuw', tekst: 'Joodse handelaren in Essaouira distribueren thee en suiker naar het binnenland; in de mellahs stoken families mahia van vijgen en dadels.' },
      { jaar: 'ca. 1900', tekst: 'Het mahia-recept van de familie Nahmias in Taznakht dateert volgens het familieverhaal uit deze tijd; een eeuw later herleeft het in de VS.' },
      { jaar: '1912', tekst: 'Frankrijk vestigt het protectoraat; in de nieuwe villes nouvelles van Casablanca en Rabat verschijnen Franse cafés met terrassen.' },
      { jaar: '1919', tekst: 'Oprichting van de Société des Brasseries du Maroc in Casablanca, tot vandaag de dominante brouwer van het land.' },
      { jaar: '1921', tekst: 'Mhamed Alouch opent Café Hafa op de kliffen van Tanger, later stamkroeg van Paul Bowles, William Burroughs en de Rolling Stones.' },
      { jaar: '1943', tekst: 'Brasseries du Maroc krijgt een notering aan de beurs van Casablanca.' },
      { jaar: 'jaren 1950', tekst: 'Hoogtepunt van de koloniale wijnbouw: circa 55.000 hectare wijngaard en ruim 3 miljoen hectoliter per jaar, grotendeels naar Frankrijk.' },
      { jaar: '1956', tekst: 'Marokko wordt onafhankelijk; Franse wijnexpertise vertrekt en met de emigratie van Joodse Marokkanen dunt de mahia-traditie uit.' },
      { jaar: '1964', tekst: 'Oprichting van Les Celliers de Meknès, dat uitgroeit tot veruit de grootste wijnproducent van het land.' },
      { jaar: '1967', tekst: 'De EEG voert importquota in en de Marokkaanse wijnexport stort in.' },
      { jaar: 'jaren 1990', tekst: 'Buitenlandse investeringen, onder meer van Franse groepen als Castel, starten de revival van de Marokkaanse wijnbouw.' },
      { jaar: '2004', tekst: "Kathy Kriger opent op 1 maart Rick's Café in een herenhuis uit 1930 aan de rand van de oude medina van Casablanca." },
      { jaar: '2012', tekst: 'Dorit en David Nahmias openen distilleerderij Nahmias et Fils in Yonkers, New York, en brengen mahia terug op de markt.' },
      { jaar: '2023', tekst: 'De licentiesamenwerking tussen Boissons du Maroc en Heineken loopt na ruim 40 jaar af in december.' },
      { jaar: '2024', tekst: 'Boissons du Maroc tekent in september een strategisch partnerschap met Carlsberg.' }
    ]
  }
};
